# Plugins
gems:             ['jekyll-paginate', 'jekyll-gist', 'jekyll-github-metadata']

# Dependencies
# highlighter:      rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Permalinks
permalink:        pretty

# Setup
title:            SLAPenrich
tagline:          Sample-population Level Analysis of Pathway enrichments
description:      "Pathway-level analysis tool set for genomics data from heterogeneous populations under positive selection"
#url:              https://github.com/saezlab/projectDocumentationTemplate
baseurl:          /SLAPenrich/
toollogo:         /SLAPenrich/public_logo.png

author:
  name:           'F. Iorio'

paginate:         5

# Custom vars
version:          1.0.1

github:
  repo:           https://github.com/saezlab/SLAPenrich
