# Plugins
gems:             ['jekyll-paginate', 'jekyll-gist', 'jekyll-github-metadata']

# Dependencies
# highlighter:      rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Permalinks
permalink:        pretty

# Setup
title:            SLAPenrich
tagline:          SLAPenrich
description:      "Sample Level Analysis of Pathway Alteration Enrichments"
#url:              https://github.com/saezlab/projectDocumentationTemplate
baseurl:          /projectDocumentationTemplate/
toollogo:         /projectDocumentationTemplate/tool_logo.png

author:
  name:           'Francesco Iorio'

paginate:         5

# Custom vars
version:          0.1.1

github:           https://github.com/saezlab/SLAPenrich/
  repo:           https://github.com/saezlab/projectDocumentationTemplate
